<a href="https://colab.research.google.com/github/ArinaKrasotina/data-analysis/blob/main/%D0%9A%D1%80%D0%B0%D1%81%D0%BE%D1%82%D0%B8%D0%BD%D0%B0_%22%D0%9A%D0%B5%D0%B9%D1%81_%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B5_%D1%81%D0%B5%D1%81%D1%81%D0%B8%D0%B8%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **3 кейс**

**Пользовательские сессии**

**Важно**

Перед началом решения выполните следующую ячейку, чтобы загрузить необходимый для работы файл.

In [1]:
!wget https://gist.github.com/Vs8th/9fcfa729905072c12b1e535c71565a68/raw/sessions.csv

--2025-12-11 11:53:15--  https://gist.github.com/Vs8th/9fcfa729905072c12b1e535c71565a68/raw/sessions.csv
Resolving gist.github.com (gist.github.com)... 20.27.177.113
Connecting to gist.github.com (gist.github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://gist.githubusercontent.com/Vs8th/9fcfa729905072c12b1e535c71565a68/raw/sessions.csv [following]
--2025-12-11 11:53:16--  https://gist.githubusercontent.com/Vs8th/9fcfa729905072c12b1e535c71565a68/raw/sessions.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1880014 (1.8M) [text/plain]
Saving to: ‘sessions.csv’

sessions.csv        100%[===================>]   1.79M  9.37MB/s    in 0.2s

2025-12-11 11:53:16 (9.37 MB/s) - ‘sessions.csv’ saved [1880014/1880014]

Чтобы посмотреть как он выглядит выполните следующую ячейку.

In [3]:
import pandas as pd

df = pd.read_csv('sessions.csv')
df

      user_id                                            session
0       user0  ["2023-05-06 20:43:45", 1192, [["page0", "2023...
1       user1  ["2023-05-03 15:39:47", 1642, [["page0", "2023...
2       user1  ["2023-05-16 21:24:30", 506, [["page0", "2023-...
3       user1  ["2023-05-09 01:41:35", 1004, [["page0", "2023...
4       user1  ["2023-05-26 05:31:50", 984, [["page0", "2023-...
...       ...                                                ...
5278  user998  ["2023-05-26 17:33:49", 631, [["page0", "2023-...
5279  user998  ["2023-05-15 23:21:39", 1393, [["page0", "2023...
5280  user998  ["2023-05-16 10:15:48", 1448, [["page0", "2023...
5281  user998  ["2023-05-26 17:06:25", 810, [["page0", "2023-...
5282  user999  ["2023-05-20 08:08:50", 744, [["page0", "2023-...

[5283 rows x 2 columns]

### **Решения**

#### **Задача 1**

Ваша задача написать функцию `get_time_to_conversion`, которая принимает на вход сессии в формате, который вы определили для себя и подсчитывает среднее время между заходом на сайт и целевым действием.

Результат - число типа `float`, округленное до двух знаков после запятой, сохраните в переменную `res`

**Решение**

Напишите свое решение ниже

In [4]:
import pandas as pd
import json
from datetime import datetime

df = pd.read_csv('sessions.csv')

def parse_session(s):
    raw = json.loads(s)

    start = datetime.fromisoformat(raw[0])
    duration = raw[1]

    pages = []
    for page, ts in raw[2]:
        pages.append((page, datetime.fromisoformat(ts)))

    return {
        "start": start,
        "duration": duration,
        "pages": pages
    }

df["parsed"] = df["session"].apply(parse_session)
sessions = df["parsed"].tolist()
df

,user_id,session,parsed
0,user0,"[""2023-05-06 20:43:45"", 1192, [[""page0"", ""2023...","{'start': 2023-05-06 20:43:45, 'duration': 119..."
1,user1,"[""2023-05-03 15:39:47"", 1642, [[""page0"", ""2023...","{'start': 2023-05-03 15:39:47, 'duration': 164..."
2,user1,"[""2023-05-16 21:24:30"", 506, [[""page0"", ""2023-...","{'start': 2023-05-16 21:24:30, 'duration': 506..."
3,user1,"[""2023-05-09 01:41:35"", 1004, [[""page0"", ""2023...","{'start': 2023-05-09 01:41:35, 'duration': 100..."
4,user1,"[""2023-05-26 05:31:50"", 984, [[""page0"", ""2023-...","{'start': 2023-05-26 05:31:50, 'duration': 984..."
...,...,...,...
5278,user998,"[""2023-05-26 17:33:49"", 631, [[""page0"", ""2023-...","{'start': 2023-05-26 17:33:49, 'duration': 631..."
5279,user998,"[""2023-05-15 23:21:39"", 1393, [[""page0"", ""2023...","{'start': 2023-05-15 23:21:39, 'duration': 139..."
5280,user998,"[""2023-05-16 10:15:48"", 1448, [[""page0"", ""2023...","{'start': 2023-05-16 10:15:48, 'duration': 144..."
5281,user998,"[""2023-05-26 17:06:25"", 810, [[""page0"", ""2023-...","{'start': 2023-05-26 17:06:25, 'duration': 810..."
5282,user999,"[""2023-05-20 08:08:50"", 744, [[""page0"", ""2023-...","{'start': 2023-05-20 08:08:50, 'duration': 744..."

In [5]:
def get_time_to_conversion(sessions):
    diffs = []

    for s in sessions:
        start = s["start"]
        for page, ts in s["pages"]:
            if page == "conversion":
                diffs.append((ts - start).total_seconds())
                break

    return round(sum(diffs) / len(diffs), 2)


res = get_time_to_conversion(sessions)
res

467.24

✏️ ✏️ ✏️

**Проверка**

Чтобы проверить свое решение, запустите код в следующих ячейках

In [6]:
try:
    assert res == 467.24
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

#### **Задача 2**

Ваша задача написать функцию `get_session_duration`, которая принимает на вход сессии в формате, который вы определили для себя и подсчитывает сколько вообще в среднем длится сессия.

Результат - число типа `float`, округленное до двух знаков после запятой, сохраните в переменную `res2`

**Решение**

Напишите свое решение ниже

In [7]:
def get_session_duration(sessions):
    durations = [s["duration"] for s in sessions]
    return round(sum(durations) / len(durations), 2)

res2 = get_session_duration(sessions)
res2

901.35

✏️ ✏️ ✏️

**Проверка**

Чтобы проверить свое решение, запустите код в следующих ячейках

In [9]:
try:
    assert res2 == 901.35
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

#### **Задача 3**

Напишите функцию `get_daily_session_count`, которая принимает на вход сессии в формате, который вы определили для себя и подсчитывает cколько разных заходов в течение дня делает пользователь.

Результат - число типа `float`, округленное до двух знаков после запятой, сохраните в переменную `res3`

**Решение**

Напишите свое решение ниже

In [10]:
def get_daily_session_count(sessions):
    day_counts = {}

    for (_, row) in df.iterrows():
        uid = row["user_id"]
        start = row["parsed"]["start"].date()

        key = (uid, start)
        day_counts[key] = day_counts.get(key, 0) + 1

    return round(sum(day_counts.values()) / len(day_counts), 2)


res3 = get_daily_session_count(sessions)
res3

1.11

✏️ ✏️ ✏️

**Проверка**

Чтобы проверить свое решение, запустите код в следующих ячейках

In [11]:
try:
    assert res3 == 1.11
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!

#### **Задача 4**

Напишите функцию `get_average_session_count`, которая принимает на вход сессии в формате, который вы определили для себя и подсчитывает сколько заходов вообще в среднем делает пользователь.

Результат - число типа `float`, округленное до двух знаков после запятой, сохраните в переменную `res4`

**Решение**

Напишите свое решение ниже

In [12]:
def get_average_session_count(sessions):
    counts = df.groupby("user_id")["session"].count().tolist()
    return round(sum(counts) / len(counts), 2)


res4 = get_average_session_count(sessions)
res4

5.28

✏️ ✏️ ✏️

**Проверка**

Чтобы проверить свое решение, запустите код в следующих ячейках

In [13]:
try:
    assert res4 == 5.28
except AssertionError:
    print('Ответы не совпадают')
else:
    print('Поздравляем, Вы справились!')

Поздравляем, Вы справились!